#!/bin/bash
###-----------------------------------------------------------------------------
cmdname=${0}
mode=${1}

if [ "${mode}" = "MONO" ]; then
    echo "${cmdname}:MONO"
    DSCUDA_SERVER="ds15:0"
elif [ "${mode}" = "POLY2" ]; then
    echo "${cmdname}:POLY2"
    DSCUDA_SERVER="ds15:0,ds16:0"
elif [ "${mode}" = "POLY3" ]; then
    echo "${cmdname}:POLY3"
    DSCUDA_SERVER="c4hdn:0,c4hdn:1,c4hdn:2"
elif [ "${mode}" = "POLY4" ]; then
    echo "${cmdname}:POLY4"
    DSCUDA_SERVER="c4hdn:0,c4hdn:1,c4hdn:2,c4hdn:3"
elif [ "${mode}" = "POLY8" ]; then
    echo "${cmdname}:POLY8"
    DSCUDA_SERVER="c4hdn:0,c4hdn:1,c4hdn:2,c4hdn:3,c5hdn:0,c5hdn:1,c5hdn:2,c5hdn:3"
else
    echo "${cmdname}:add MONO or POLYn for 1st parameter"
    exit 1
fi
export DSCUDA_SERVER

export CUDAPATH=/usr/local/cuda-4.2
export CUDASDKPATH=~/NVIDIA_GPU_Computing_SDK
export DSCUDA_PATH=~/dscudapkg_FT
export DSCUDA_WARNLEVEL=10
export DSCUDA_REMOTECALL="rpc"

export DSCUDA_USEDAEMON=1
export DSCUDA_AUTOVERB=0
export DSCUDA_MIGRATION=0
export LD_LIBRARY_PATH=$DSCUDA_PATH/lib:$CUDAPATH/lib64:$CUDAPATH/lib:$LD_LIBRARY_PATH
export PATH=$DSCUDA_PATH/src:$CUDAPATH/bin:$PATH
export OMP_NUM_THREADS=1

#~/bin/env_dscuda

#gnome-terminal -e "bash -c ./dslogmon" &> /dev/null & 
#xterm -e "bash -c ./dslogmon" -geometry 105x25+0+0 &> /dev/null &
gnome-terminal --geometry=105x25+0+0 -e "bash -c ./dslogmon" &> /dev/null & 

./vecadd_rpc
#gdb -tui ./vecadd_rpc

#./vecadd_rpc 2>&1 | tee vecadd_rpc.log
#emacs vecadd.cu

