#!/bin/bash

export CUDAPATH=/usr/local/cuda-4.2
export CUDASDKPATH=~/NVIDIA_GPU_Computing_SDK
export DSCUDA_PATH=~/dscudapkg
export DSCUDA_WARNLEVEL=10
export DSCUDA_REMOTECALL="rpc"

export DSCUDA_SERVER="stelletto2:0,c4hdn:0"

#export DSCUDA_SERVER="stelletto2:0 stelletto2:1 stelletto2:2 stelletto2:3 \
#c4hdn:0 c4hdn:1 c4hdn:2 c4hdn:3 \
#c5hdn:0 c5hdn:1 c5hdn:2 c5hdn:3"

#export DSCUDA_SERVER="c4hdn:0"
#export DSCUDA_SERVER="10.68.209.6:0"
#export DSCUDA_SERVER="kaust_6"
#export DSCUDA_SERVER="titan05:0"
#export DSCUDA_SERVER="titan05:0,titan06:0"
#export DSCUDA_SERVER="titan05:0,titan06:0,titan07:0"

export DSCUDA_USEDAEMON=1
export DSCUDA_AUTOVERB=0
export DSCUDA_MIGRATION=0
export LD_LIBRARY_PATH=$DSCUDA_PATH/lib:$CUDAPATH/lib64:$CUDAPATH/lib:$LD_LIBRARY_PATH
export PATH=$DSCUDA_PATH/src:$CUDAPATH/bin:$PATH
export OMP_NUM_THREADS=1

#~/bin/env_dscuda

./vecadd_rpc 2>&1 | tee vecadd_rpc.log
#emacs vecadd.cu 
